name: 'Chromatic'

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: github.event_name != 'merge_group'
        id: cache
        with:
          path: |
            node_modules
            */**/node_modules
          key:
            ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock',
            'packages/**/yarn.lock') }}
      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: 0
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn build
      - name: Check generated styles
        run: |
          yarn carbon-cli check --ignore '**/@(node_modules|examples|components|react|fixtures|compat)/**' 'packages/**/*.scss'

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/react
          buildScriptName: storybook:build
          onlyChanged: true
